### ISSUE TITLE
无法访问

### ISSUE THREAD

**Issue by yuehun** [qianjiachun/douyu-monitor#1]
![YY截图20211220221529](https://user-images.githubusercontent.com/24507941/146780934-a6f2086d-6286-4fe6-b15e-4acba1444f21.png)
![YY截图20211220221605](https://user-images.githubusercontent.com/24507941/146780944-df4e8191-d902-43e8-b8e2-2f20999ebf05.png)

**Comment by qianjiachun** [comment]
。。。你在服务器上开局域网服务器，然后用公网访问肯定失败啊。  
正确的做法是  

1. `npm run build`
2. 将dist文件夹作为网页发布

**Comment by yuehun** [comment]
> ......你在服务器上开局域网服务器，然后用公网访问肯定失败啊。 正确的做法是
> 
> 1. `npm run build`
> 2. 将dist文件夹作为网页发布


![YY截图20211221002052](https://user-images.githubusercontent.com/24507941/146799191-fc40d68c-aed6-455c-ba13-1db24f445a2d.png)

![YY截图20211221001911](https://user-images.githubusercontent.com/24507941/146798970-3d9f1532-ec76-470b-9977-5b649f9de7b4.png)
诶，不会搞，这又是哪里出问题了，大佬

**Comment by qianjiachun** [comment]
网站搭建成功后，需要在nginx下做一次重定向    
代码如下，添加到nginx配置中即可  
```
location / {
     try_files $uri $uri/ /index.html;
}
```

**Comment by yuehun** [comment]
> 网站搭建成功后，在nginx下做一次创建 如下代码，添加到nginx配置中分类
> 
> ```
> location / {
>      try_files $uri $uri/ /index.html;
> }
> ```



感谢感谢，可以了
