### ISSUE TITLE
可以延伸成房间管理工具

### ISSUE THREAD

**Issue by ChaosTong** [qianjiachun/douyu-monitor#5]
![截屏2022-07-27 09 30 34](https://user-images.githubusercontent.com/3345527/181140829-f3e44c79-3415-41f4-8341-4d48c6599d77.png)
小小扩展了一下, 点击一条弹幕查询发言记录(接口自己写的).
如果有房间房管的话, 带上cookie调用douyu封禁接口, 加上自建一套账户体系的理论上可以扩充无限房管

**Comment by qianjiachun** [comment]
非常不错呀！不过此举我认为不适合并入主分支😂
这个产品我个人定位是"view"部分，也就是更偏向于"看"，作为管理端似乎就有些重了。后续我也是准备加入新的模块（弹幕礼物入场混合）用于OBS等直播工具内更好地显示，这项工作应该会在年底前完成。

项目为了最大程度的可扩展性本应该是纯前端应用的，也就是说完全是静态页面。不过为了动态获取房间号和礼物数据做了妥协，我尚不知remix和electron之类结合的可行性（已有vue版本的[DIY repo](https://github.com/ReCh4rge/dy-flyby-proxy)）。所以以此初衷，后续功能更多的是重前端。

关于你的提议我觉得可以在管理方面大有可为。完全能够另起一个分支项目，做成重后端的项目😊

**Comment by ChaosTong** [comment]
其实几年前我已经写过这样的系统并且在某个大主播房间使用了两年, 只是我看到你写的挺好的, 然后尝试了简单魔改下, 确实可行, 当时我也是这个思路但是翻遍了 Github 没有类似的项目, 只能自己瞎写了(本人iOS程序员), 要是当时有你这个就好写多了.
只是想和你分享一下我的使用场景😄, 没想着合并代码呢😂, 我现 Google 的 Vue 父传子 子传父 组件传值 Axios 请求网络, 然后复用了弹幕区的组件.

**Comment by qianjiachun** [comment]
👍好的，加油！
另外有条件的话建议还是使用[remix版本](https://github.com/qianjiachun/douyu-monitor/tree/main/remix)，vue版本已经不维护啦而且写的好像有点乱😂
