### ISSUE TITLE
[功能请求] 增加可交互的元素

### ISSUE THREAD

**Issue by Mishasama** [qianjiachun/douyu-monitor#8]
现在整个画面都只能通过点击弹出的面板进行一些参数上的调整，但无法对画面上的条目进行任何操作。
希望能像官方直播间页面那样提供一些便捷的功能。

1. 文字可拖选。比如选择部分文字进行复制，方便主播复制一些弹幕提供的内容进行其他操作。
2. 用户名点击跳转到用户的空间页面。方便用户进行进一步的操作。比如关注、私信等。
3. 增加一个把所有数据都写到浏览器的网站储存空间里，并且可以通过菜单的功能按钮进行导出到 TXT 或 JSON 文件。方便保留关键数据。甚至用于未来进行回放、做视频字幕等操作。当然，最好是刷新页面后自动清理上次保留的数据，甚至提供按钮进行手动清理，避免炸库。
4. 如果能利用起浏览器的 TTS 引擎读出各种条目就更完美了。

上述功能应该还是属于 viewer 的范畴之内，我想你应该是想做一个能集成在 OBS 里的浮层吧？那么这些功能对主播来说还是挺有用的，能在一定程度上作为伴侣显示弹幕的平替。

**Comment by qianjiachun** [comment]
感谢建议，这些需求我都会认真考虑的。只是最近时间精力有限，可能暂时没办法维护😂，后面有空了看一下
